
const supabaseUrl = "https://bvvgfsogkzaikpraluof.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dmdmc29na3phaWtwcmFsdW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcwMjYwMDAsImV4cCI6MjA5MjYwMjAwMH0.Rv4gjwqFA_ZVyice9JBV7sf81alsZb3PmB3lVtS4Xjo";
const client = window.supabase.createClient(supabaseUrl, supabaseKey);

let currentExamId=null,currentExamTitle="",currentPreviewExam=null;
let solvingQuestions=[],currentQuestionIndex=0,studentAnswers={},reviewLater={},timerInterval=null,remainingSeconds=0;

function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const x=document.getElementById(id);if(x)x.classList.add('active');}
async function goDashboard(){const {data}=await client.auth.getUser();const u=data.user;if(!u){location.href='login.html';return;}(u.user_metadata?.role==='teacher')?showPage('teacherDashboard'):showPage('studentDashboard');}
async function logout(){await client.auth.signOut();location.href='login.html';}

async function createExam(){const title=examTitle.value.trim(),description=examDesc.value.trim(),timeLimit=Number(examTime.value||10);if(!title){examMsg.textContent='Please enter title';return;}const {data}=await client.auth.getUser();const u=data.user;if(!u){examMsg.textContent='Login first';return;}examMsg.textContent='Creating...';const r=await client.from('exams').insert([{title,description,time_limit:timeLimit,teacher_id:u.id}]);if(r.error){examMsg.textContent=r.error.message;console.error(r.error);return;}examMsg.textContent='Exam created ✅';examTitle.value='';examDesc.value='';examTime.value=10;loadTeacherExams();}
async function loadTeacherExams(){teacherExamList.innerHTML='Loading...';const {data}=await client.auth.getUser();const u=data.user;if(!u)return;const r=await client.from('exams').select('*').eq('teacher_id',u.id).order('created_at',{ascending:false});if(r.error){teacherExamList.innerHTML='Error';console.error(r.error);return;}const rows=r.data||[];teacherExamList.innerHTML=rows.length?'':'No exams yet';rows.forEach(exam=>{const d=document.createElement('div');d.className='box';d.innerHTML=`<h3>${exam.title}</h3><p>${exam.description||''}</p><p>⏱ ${exam.time_limit||10} min</p>`;const b=document.createElement('button');b.textContent='Manage Questions';b.onclick=()=>openQuestionManager(exam.id,exam.title);d.appendChild(b);teacherExamList.appendChild(d);});}
function handleQuestionTypeChange(){mcqOptions.style.display=questionType.value==='mcq'?'block':'none';trueFalseOptions.style.display=questionType.value==='true_false'?'block':'none';}
function openQuestionManager(id,title){currentExamId=id;currentExamTitle=title||'';questionExamTitle.textContent='Manage Questions: '+currentExamTitle;showPage('questionManager');loadQuestions();}
async function addQuestion(){if(!currentExamId){questionMsg.textContent='Choose exam first';return;}const type=questionType.value,text=questionText.value.trim(),explanation=questionExplanation.value.trim();if(!text){questionMsg.textContent='Enter question';return;}let row={exam_id:currentExamId,question_text:text,question_type:type,explanation};if(type==='mcq'){if(!optionA.value||!optionB.value||!optionC.value||!optionD.value){questionMsg.textContent='Fill options';return;}Object.assign(row,{option_a:optionA.value.trim(),option_b:optionB.value.trim(),option_c:optionC.value.trim(),option_d:optionD.value.trim(),correct_answer:mcqCorrectAnswer.value});}else{Object.assign(row,{option_a:'True',option_b:'False',correct_answer:tfCorrectAnswer.value});}const r=await client.from('questions').insert([row]);if(r.error){questionMsg.textContent=r.error.message;console.error(r.error);return;}questionMsg.textContent='Saved ✅';questionText.value=optionA.value=optionB.value=optionC.value=optionD.value=questionExplanation.value='';loadQuestions();}
async function loadQuestions(){questionList.innerHTML='Loading...';const r=await client.from('questions').select('*').eq('exam_id',currentExamId).order('created_at',{ascending:true});if(r.error){questionList.innerHTML='Error';return;}const qs=r.data||[];questionList.innerHTML=qs.length?'':'No questions yet';qs.forEach((q,i)=>{const box=document.createElement('div');box.className='box';box.innerHTML=`<h3>${i+1}. ${q.question_text}</h3><p><b>Correct:</b> ${q.correct_answer}</p><p>${q.explanation||''}</p>`;questionList.appendChild(box);});}

async function loadStudentExams(){studentExamList.innerHTML='Loading exams...';const r=await client.from('exams').select('*').order('created_at',{ascending:false});if(r.error){studentExamList.innerHTML='Error loading exams';console.error(r.error);return;}const exams=r.data||[];studentExamList.innerHTML=exams.length?'':'No exams yet';exams.forEach(exam=>{const box=document.createElement('div');box.className='box';box.innerHTML=`<h3>${exam.title}</h3><p>${exam.description||''}</p><p><b>⏱ Time:</b> ${exam.time_limit||10} min</p>`;const btn=document.createElement('button');btn.textContent='Start Exam 🚀';btn.onclick=()=>previewExam(exam.id,exam.title,exam.description,exam.time_limit);box.appendChild(btn);studentExamList.appendChild(box);});}
function previewExam(id,title,description,timeLimit){currentPreviewExam={id,title,description,timeLimit:Number(timeLimit||10)};takeExamTitle.textContent=title||'Exam';takeExamDesc.textContent=description||'';takeExamTime.textContent='Time limit: '+(timeLimit||10)+' minutes';showPage('takeExam');}
async function startSolvingExam(){if(!currentPreviewExam)return;const r=await client.from('questions').select('*').eq('exam_id',currentPreviewExam.id).order('created_at',{ascending:true});if(r.error){alert('Error loading questions');return;}solvingQuestions=r.data||[];if(!solvingQuestions.length){alert('This exam has no questions yet.');return;}currentQuestionIndex=0;studentAnswers={};reviewLater={};remainingSeconds=currentPreviewExam.timeLimit*60;solverExamTitle.textContent=currentPreviewExam.title||'Exam';showPage('examSolver');startTimer();renderSolver();}
function startTimer(){if(timerInterval)clearInterval(timerInterval);updateTimerText();timerInterval=setInterval(()=>{remainingSeconds--;updateTimerText();if(remainingSeconds<=0){clearInterval(timerInterval);submitExam(true);}},1000);}
function updateTimerText(){const m=Math.floor(remainingSeconds/60),s=remainingSeconds%60;examTimer.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}
function renderSolver(){const q=solvingQuestions[currentQuestionIndex];if(!q)return;renderQuestionNav();solverQuestionText.textContent=(currentQuestionIndex+1)+'. '+q.question_text;solverOptions.innerHTML='';const opts=q.question_type==='true_false'?[{key:'True',text:'True'},{key:'False',text:'False'}]:[{key:'A',text:q.option_a},{key:'B',text:q.option_b},{key:'C',text:q.option_c},{key:'D',text:q.option_d}];opts.forEach(o=>{const lab=document.createElement('label');lab.className='option-card';lab.innerHTML=`<input type="radio" name="answer" ${studentAnswers[q.id]===o.key?'checked':''}> <b>${o.key}.</b> ${o.text||''}`;lab.onclick=()=>{studentAnswers[q.id]=o.key;renderQuestionNav();};solverOptions.appendChild(lab);});}
function renderQuestionNav(){questionNav.innerHTML='';solvingQuestions.forEach((q,i)=>{const p=document.createElement('div');p.className='question-pill';if(i===currentQuestionIndex)p.classList.add('active');if(studentAnswers[q.id])p.classList.add('answered');if(reviewLater[q.id])p.classList.add('review');p.textContent=i+1;p.onclick=()=>{currentQuestionIndex=i;renderSolver();};questionNav.appendChild(p);});}
function nextQuestion(){if(currentQuestionIndex<solvingQuestions.length-1){currentQuestionIndex++;renderSolver();}}
function previousQuestion(){if(currentQuestionIndex>0){currentQuestionIndex--;renderSolver();}}
function toggleReviewLater(){const q=solvingQuestions[currentQuestionIndex];reviewLater[q.id]=!reviewLater[q.id];renderQuestionNav();}

async function submitExam(autoSubmit){if(!autoSubmit&&!confirm('Submit exam now?'))return;if(timerInterval)clearInterval(timerInterval);let correct=0;const answers=[];solvingQuestions.forEach(q=>{const ans=studentAnswers[q.id]||null,ok=ans===q.correct_answer;if(ok)correct++;answers.push({question_id:q.id,question_text:q.question_text,student_answer:ans,correct_answer:q.correct_answer,is_correct:ok,explanation:q.explanation||''});});const total=solvingQuestions.length,percentage=Math.round((correct/total)*100);await saveExamResult(correct,total,percentage,answers);resultTitle.textContent=currentPreviewExam.title||'Result';scoreText.textContent=`Your score: ${correct} / ${total} (${percentage}%)`;studyAdviceAfterResult.innerHTML=getStudyAdvice(percentage);resultDetails.innerHTML='';answers.forEach((a,i)=>{const div=document.createElement('div');div.className='box '+(a.is_correct?'correct':'wrong');div.innerHTML=`<h3>${i+1}. ${a.question_text}</h3><p><b>Your answer:</b> ${a.student_answer||'No answer'}</p><p><b>Correct:</b> ${a.correct_answer}</p><p><b>Explanation:</b> ${a.explanation||'-'}</p>`;resultDetails.appendChild(div);});showPage('examResult');}
function getStudyAdvice(p){if(p<50)return '<h2>Study Advice</h2><p>Review basics first: grammar rules, vocabulary meanings, and solve easy questions again.</p>';if(p<80)return '<h2>Study Advice</h2><p>Good work. Focus on your mistakes and practise timed questions.</p>';return '<h2>Study Advice</h2><p>Excellent. Move to advanced questions and teach the idea to someone else.</p>';}
async function saveExamResult(score,total,percentage,answers){const {data}=await client.auth.getUser();const u=data.user;if(!u||!currentPreviewExam)return;const r=await client.from('exam_results').insert([{student_id:u.id,exam_id:currentPreviewExam.id,score,total,percentage,answers}]);if(r.error)console.warn(r.error.message);}

async function loadMyResults(){myResultsList.innerHTML='Loading...';const {data}=await client.auth.getUser();const u=data.user;if(!u)return;const r=await client.from('exam_results').select('*, exams(title)').eq('student_id',u.id).order('created_at',{ascending:false});if(r.error){myResultsList.innerHTML='Error';return;}const rows=r.data||[];myResultsList.innerHTML=rows.length?'':'No results yet';rows.forEach(x=>{const d=document.createElement('div');d.className='box';d.innerHTML=`<h3>${x.exams?.title||'Exam'}</h3><p>Score: ${x.score}/${x.total} (${x.percentage}%)</p><p>${new Date(x.created_at).toLocaleString()}</p>`;myResultsList.appendChild(d);});}
async function loadTeacherResults(){teacherResultsList.innerHTML='Loading...';const r=await client.from('exam_results').select('*, exams(title)').order('created_at',{ascending:false});if(r.error){teacherResultsList.innerHTML='Error or no table';return;}teacherResultsList.innerHTML='';(r.data||[]).forEach(x=>{const d=document.createElement('div');d.className='box';d.innerHTML=`<h3>${x.exams?.title||'Exam'}</h3><p>Score: ${x.score}/${x.total} (${x.percentage}%)</p>`;teacherResultsList.appendChild(d);});}
async function loadLeaderboard(type){leaderboardList.innerHTML='Loading...';const start=new Date();if(type==='daily')start.setHours(0,0,0,0);else start.setDate(start.getDate()-7);const r=await client.from('exam_results').select('*, exams(title)').gte('created_at',start.toISOString()).order('percentage',{ascending:false}).order('score',{ascending:false});if(r.error){leaderboardList.innerHTML='Error';return;}leaderboardList.innerHTML=`<h2>${type==='daily'?'Daily':'Weekly'} Leaderboard 🏆</h2>`;(r.data||[]).forEach((x,i)=>{const medal=i===0?'🥇':i===1?'🥈':i===2?'🥉':'#'+(i+1);const d=document.createElement('div');d.className='box';d.innerHTML=`<h3>${medal} Student</h3><p>${x.exams?.title||'Exam'}</p><p>${x.score}/${x.total} (${x.percentage}%)</p>`;leaderboardList.appendChild(d);});}

function localAssistant(){const q=assistantQuestion.value.toLowerCase();let ans='Start by identifying your weak point, then practise with short timed exercises.';if(q.includes('grammar'))ans='For grammar: learn the rule, write 3 examples, then solve 10 mixed questions.';if(q.includes('vocab'))ans='For vocabulary: use word + meaning + sentence + quick revision after 24 hours.';if(q.includes('plan'))ans='Use 25 minutes study + 5 minutes break. Start with the hardest subject first.';assistantAnswer.innerHTML='<h3>JAK Assistant</h3><p>'+ans+'</p>';}
function mockAIQuestions(){const topic=aiTopic.value||'English';const count=Number(aiCount.value||5);aiPreview.innerHTML='';for(let i=1;i<=count;i++)aiPreview.innerHTML+=`<div class="box"><b>${i}.</b> Sample ${aiType.value} question about ${topic}.</div>`;}
function insertMath(t){mathEditor.value += (mathEditor.value?' ':'')+t;}
const syms=['√','π','∞','≤','≥','≠','≈','±','×','÷','∑','∆','θ','α','β','x²','x³','∫'];
window.addEventListener('load',()=>{if(document.getElementById('mathSymbols'))syms.forEach(s=>{const b=document.createElement('button');b.textContent=s;b.onclick=()=>insertMath(s);mathSymbols.appendChild(b);});});

function openPlanner(){showPage('planner');loadPlans();renderCalendar();}
function getPlans(){return JSON.parse(localStorage.getItem('jakPlansV4'))||[];}
function savePlans(p){localStorage.setItem('jakPlansV4',JSON.stringify(p));}
function addPlan(){const p={subject:subject.value.trim(),date:studyDate.value,start:startTime.value,end:endTime.value,type:planType.value,task:task.value.trim()};if(!p.subject||!p.date||!p.start||!p.end){alert('Fill all fields');return;}const plans=getPlans();if(p.type==='daily')for(let i=0;i<7;i++){const d=new Date(p.date);d.setDate(d.getDate()+i);plans.push({...p,date:d.toISOString().split('T')[0]});}else plans.push(p);savePlans(plans);subject.value=studyDate.value=startTime.value=endTime.value=task.value='';loadPlans();renderCalendar();}
function loadPlans(){const plans=getPlans().sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));plansList.innerHTML=plans.length?'':'No plans yet';plans.forEach((p,i)=>{const d=document.createElement('div');d.className='box';d.innerHTML=`<span class="badge">${p.type}</span><h3>${p.subject}</h3><p>📅 ${p.date}</p><p>⏰ ${p.start} → ${p.end}</p><p>${p.task||''}</p><button class="danger" onclick="deletePlan(${i})">Delete</button>`;plansList.appendChild(d);});}
function deletePlan(i){const p=getPlans();p.splice(i,1);savePlans(p);loadPlans();renderCalendar();}
function clearAllPlans(){if(confirm('Delete all plans?')){localStorage.removeItem('jakPlansV4');loadPlans();renderCalendar();}}
function renderCalendar(){const plans=getPlans();calendarView.innerHTML=plans.length?'<div class="calendar-grid"></div>':'No plans yet';const grid=calendarView.querySelector('.calendar-grid');if(!grid)return;const g={};plans.forEach(p=>{if(!g[p.date])g[p.date]=[];g[p.date].push(p);});Object.keys(g).sort().forEach(date=>{const day=document.createElement('div');day.className='calendar-day';day.innerHTML='<b>📅 '+date+'</b>';g[date].forEach(p=>day.innerHTML+=`<div class="mini-plan ${p.type}"><b>${p.subject}</b><br>${p.start} → ${p.end}<br>${p.task||''}</div>`);grid.appendChild(day);});}
function printPlans(){openPlanner();window.print();}

showPage('home');
